---
title: "Data used in ES 218"
output: html_document
---

* CO2 (1959-2014): [file](./Data/CO2.csv), [README](./Data/CO2_readme.txt)
* Southern oscillation index (1960-2014): [file](./Data/Southern_oscillation.csv), [README](./Data/Southern_oscillation_readme.txt)
* Pacific decadal oscillation index (1900-2001): [file](./Data/PDO.dat), [README](./Data/PDO_readme.txt)
* ACS Income and Education (2008-2012): [file (CSV)](./Data/ACS.csv), [file (RDS)](./Data/ACS.rds), [Code book](./Data/ACS_CodeBook.csv)
* Income by educational attainment (2008 - 2012): [file (CSV)](./Data/Income_education.csv), [file with FIPS (CSV)](./Data/Income_education_with_FIPS.csv), [Code book](./Data/Income_education_codebook.csv)
* Population (1850-2013): [file](./Data/Population.csv), [README](Population_readme.txt)
* Colby courses (Spring 2015): [file](./Data/colby_sp2015.csv), [Department/Division key](./Data/Divisions.csv)
* Seeded clouds: [file](./Data/Rainfall_cloud_seeding.csv), [README](./Data/Rainfall_cloud_seeding.txt)
* GHCND temperature data for five US locations: [file](./Data/GHCND.csv), [README](./Data/GHCND_readme.txt), [Documentation](./Data/GHCND_documentation.pdf)
* Historical temperature data for New York: [file](./Data/NewYork.csv), [README](./Data/NewYork_readme.txt)
* Historical temperature data for Bombay: [file](./Data/Bombay.csv), [README](./Data/Bombay_readme.txt)
* Historical temperature data for Shanghai: [file](./Data/Shanghai.csv), [README](./Data/Shanghai_readme.txt)
* Gulf of Maine buoy data (2012): [file](./Data/buoy_44005_2012.dat), [README](./Data/buoy_44005_2012_README.txt)
* Gulf of Maine buoy data (1905 - 2012): [file](./Data/GoM_hist.csv)
* Kennebec River daily discharge (2004 - 2014): [file (xlsx)](./Date/Discharge_2004_2014.xlsx), [README](./Data/Discharge_2004_2014_readme.txt)
* NFL Combine: [file](./Data/NFLcombine.csv), [README](./Data/NFLcombine_readme.txt)
* Uninsured by county: [file](./Data/Uninsured.csv), [README](./Data/Uninsured_readme.txt)
* Greenhouse gas emissions for the northeast (2008 & 2011): [file](./Data/NEI_2008_2011.csv), [README](./Data/NEI_2008_2011_README.txt)
* North american grain production (1961-2012): [file](./Data/FAO_grains_NA.csv), [README](./Data/FAO_grains_NA_README.txt) 
* Logan airport (BOS) flight data (2014): [file](./Data/BOS_2014.csv), [README](./Data/BOS_2014_readme.txt)
* Consumer expenditure (1995-2012): [file](./Data/cex1.csv), [README](./Data/cex1_README.txt)
* William Cleveland's fusion time data: [file](./Data/fusion.csv)
* William Cleveland's food web data: [file](./Data/Food_web.csv)
* William Cleveland's ganglion data: [file](./Data/ganglion.csv)
* William Cleveland's figure 3.6 data: [file](./Data/Cleveland36.csv)
* William Cleveland's carbon dating data: [file](./Data/carbon_dating.csv)
* In-class sample data 1: [file](./Data/Sample1.csv)
