---
title: ""
output: 
   html_document:
      toc: no
---

<p style="color: #555599;margin-top:10px;font-weight: 400;font-size:2em; ">
Exploratory Data Analysis in R
</p>

<p style="color: #595959;margin-top:10px;">
This repo houses lecture notes used in an *Exploratory Data Analysis in R* course taught to undergraduates at Colby College. The course assumes little to no background in quantitative analysis nor in computer programming and was first taught in Spring, 2015. The course introduces students to data manipulation in R, data exploration (in the spirit of John Tukey's EDA) and the R markdown language. Many of the visualization tools are adopted from William Cleveland's *Data Visualization* book.
</p>



# Week 1  

#### [Course introduction](Week01.html) 
#### [The R and R Studio environments](The_R_environment.html)
 * Command line vs. script file
 * Packages
     + Base packages
     + Installing packages from CRAN
     + Installing packages from GitHub
     + Using a package in a R session
 * Getting a session's info 
 * A brief [video intro](Videos/RStudio_environ1.webm) to the RStudio environment 

#### [Maintaining a tidy project environment](The_R_environment.html#project-directory-structure)

#### Some useful links 

  * For R programming questions, a wonderful (peer-reviewed) forum is http://stackoverflow.com/ (add the `[r]` label in the search box to limit the search to R related topics).
  * For statistical questions, search the http://stats.stackexchange.com forum (here too add the `[r]` label in the search box to limit the search to R related topics)
  * A very nice repository of R related blogs is http://R-bloggers.com 
  * If you are on the Colby network, you can access the **Use R!**  online books series at http://link.springer.com/bookseries/6991
 
# Week 2  
#### [Data object type and structure](Week02a.html)  
 * Data types (aka mode) in R: numeric, character, factor, logical, dates  
 * Data objects in R: vector, data frame, lists
 * Coercing data from one type to another
 
#### [How to read and create data files in R](Week02b.html)  
 * Reading/writing files: comma delimited (CSV), tab delimited, R files
 * Data can be loaded from a file residing on your local drive or on the web 
 * Importing files from other formats such as Excel, STATA and SAS

#### [Working with Date objects](Week02c.html)  
 * Creating date/time objects using `lubridate`
 * Extracting data information
 * Concatenating vectors with `paste`
 * Operating on dates
 * Formatting date objects
 
#### [Exploring and cleaning dataframes using base functions](Week02d.html) 
 * Exploring the table with `dim`, `names`, `head`, `str` and `summary`
 * Deleting columns
 * Replacing values with `NA` [[video](./Videos/Replace_99_with_NA.mp4)]
 * The matching operator `%in%` [[video](./Videos/Matching_operator.mp4)]
 * The Boolean operators `&`, `|` and `!`

# Week 3

#### [Manipulating dataframes with `dplyr`](Week03a.html)
 * Subsetting by row values: `filter`
 * Subsetting columns: `select`
 * Computing and/or adding columns: `mutate`
 * Summarizing by category: `group_by` and `summarise`
 * Sorting by column values: `arrange`
 * Combining operations using the pipe `%>%` operator
      
#### [Tidying/reshaping tables using `tidyr`](Week03b.html) 
  * From long to wide: `spread`
  * From wide to long: `gather`
  * Combining columns: `unite`
  * Splitting columns: `separate`
  * Adding missing records: `complete`

# Week 4
  
#### [Joining data tables](Week03c.html)
  * Left join
  * Right join
  * Inner join
  * Full join

#### [Working with string objects](Week03d.html)
  * Finding patterns in a string
  * Modifying strings
  * Extracting parts of a string

# Week 5

#### [The base plotting environment](Week04a.html) 
  * Point and line plots
  * Boxplots
  * Histograms
  * Density plot
  * Point and line symbols
  * Exporting to files (tiff and PDF)
   
#### [The `lattice` plotting environment](Week04b.html) 
  * Conditioning on factors
  * Displaying univariate data
  * Displaying multivariate data
  * Customizing trellis plots
  
#### [The `ggplot` plotting environment](Week04c.html) 
  * Line geometry `geom_line`
  * Point geometry `geom_point`
  * Boxplot geometry `geom_boxplot`
  * Histogram geometry `geom_histograms`
  * Violin plot geometry `geom_violin`
  * Combining geometries and layers
  * Faceting plots (trellis plots)
  
#### [Manipulating colors in R](Week04d.html)
  * The `rgb()` function
  
# Week 6

#### The R Markdown language
  
  * [R Markdown basics](http://rmarkdown.rstudio.com/) (external site)
  * [An R markdown file example: Buoy data report](./Data/Sample_markdown_file.Rmd)

#### [Visualizing univariate data](Week05a.html)

  * Boxplots
  * Histograms
  * Quantile plots

#### [Comparing univariate data distributions](Week05b.html)

  * Side-by-side boxplots
  * Quantile-quantile plots (q-q) 
  * Tukey mean-difference plots (m-d)

# Week 7

#### [The theoretical q-q plot](Week06a.html)

   * Imposing a structure: the normal distribution


# Week 8

#### [Fits and residuals](Week07a.html)

  * Fitting univariate  data
  * Extracting the residuals
  * Residual-fit spread plot

#### [Spread-location plot](Week07b.html)

  * Detecting changes in the spread
  * Interpreting and s-l plot

# Week 9

#### [Re-expressing data](Week08a.html)
 
  * Log transformation
  * Box-Cox family of transformations
  * How quantile plots behave in the face of skewed data

#### [Letter value summaries](Week08b.html)

  * Constructing letter value summaries
  * Interpreting letter value summaries

#### [The Two R's of EDA](Week08c.html)
   * Robustness
   * Re-expression

# Week 10

#### [Bivariate analysis](Week09a.html)
  * Scatter plots
  * Fitting the data
     + Parametric fit
     + LOESS fit
  * Residuals
     + Residual dependence plot
     + spread-location plot

#### [Resistant lines](Week09b.html)
  * Robust lines
    + Tukey's 3-point summary
    + Bisquare estimation method
  * Robust loess


# Week 11

#### [The third R of EDA: Residuals](Week10a.html)
  * Exploring atmospheric CO2 data
  
#### [Detecting discontinuities in the data](Week10b.html)
  * Slicing data
  * Changepoint detection

# Week 12

#### [Two-way tables](Week11a.html)
   * Median polish
   * ANOVA analysis

#### [Details of an ANOVA (optional reading)](http://mgimond.github.io/Stats-in-R/ANOVA.html 
 
#### [Details of OLS regression method (optional reading)](http://mgimond.github.io/Stats-in-R/Regression.html) 

# Week 13

#### [Creating maps in R](Week13a.html)
   * Using `maps` package datasets
   * Loading custom shapefiles
   * continuous vs. discrete color schemes

#### Relational databases
   * Querying with `SQL`
   * Querying with `dplyr`

# Software version

```{r echo=FALSE}
pander::pander(paste("This site was built with R ", getRversion(), " and the following packages:\n\n"))

devtools::session_info(pkgs=c("dplyr","tidyr","ggplot2", "lattice", "lubridate", "readxl", "stringr"), include_base = FALSE)[[2]]
```

   


