<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>18&nbsp; The Empirical QQ Plot – Exploratory Data Analysis in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./theoretical_qq.html" rel="next">
<link href="./univariate_plots.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-7088963c8dc805b59bde81e27df5a3b9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-CJW3PSXZC2"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-CJW3PSXZC2', { 'anonymize_ip': true});
</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="libs/style.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./univariate_preamble.html">Univariate</a></li><li class="breadcrumb-item"><a href="./compare_batches.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">The Empirical QQ Plot</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./"></a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Intro</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">EDA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./The_R_environment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The R and RStudio Environments</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Data manipulation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_objects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Object Type and Structure</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./read_write_files.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Reading and Writing Data Files</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./date_objects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Working with Dates</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./strings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Working with Strings</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./boolean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Relational and boolean operations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./subset_base.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Manipulating data tables using base functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Manipulating data tables with <code>dplyr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./group_by.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Grouping and summarizing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tidyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Tidying/reshaping tables with <code>tidyr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./joins.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Joining Data Tables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Plots</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./base_plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Base plotting environment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lattice_plot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Lattice plotting environment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ggplot2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">ggplot2 plotting environment</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Univariate</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./univariate_preamble.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Univariate EDA preamble</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./univariate_plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Visualizing Univariate Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./compare_batches.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">The Empirical QQ Plot</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./theoretical_qq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">The Theoretical QQ Plot</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./residuals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Fitting and Residuals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rf.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Visualizing Explained and Unexplained Variation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./re_express.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Transforming data: Re-expression for Shape and Spread</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sl_plot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Diagnosing Unequal Spread: Spread-Location and Spread-Level Plots</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./letter_values.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Beyond the Boxplot: Tukey’s Letter-Value Summaries</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Bivariate</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bivariate_preamble.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Bivariate EDA Preamble</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bivariate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Fitting and Exploring Bivariate Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./non_parametric_loess.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Non-parametric Bivariate Modeling with Loess</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bivariate_residuals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Model Residuals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bivariate_sl_plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Exploring Spread in the Residuals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bivariate_vd_plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Visualizing Variability Decomposition in Bivariate Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bivariate_rf_plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Bivariate Residual-Fit Spread Plot</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bivariate_theo_plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Parameterizing the Residuals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bivariate_reexpression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Refining Bivariate Models Through Re-expression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resistant_lines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Robust Regression: Resistant Lines and Beyond</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discontinuity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Slicing Data: Exploring Discontinuities and Local Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">A Deeper Exploration of Residuals: Revealing Hidden Structure</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Two-way tables</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./two_way.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Analyzing Two-Way Tables: The Median Polish</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Miscellaneous</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rmarkdown.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">R Markdown</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./spatial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Mapping variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./supporting_functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Supporting Functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Data used in ES218</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-empirical-quantile-quantile-qq-plot" id="toc-the-empirical-quantile-quantile-qq-plot" class="nav-link active" data-scroll-target="#the-empirical-quantile-quantile-qq-plot"><span class="header-section-number">18.1</span> The empirical quantile-quantile (QQ) plot</a>
  <ul class="collapse">
  <li><a href="#qq-plots-vs.-bivariate-scatter-plots" id="toc-qq-plots-vs.-bivariate-scatter-plots" class="nav-link" data-scroll-target="#qq-plots-vs.-bivariate-scatter-plots"><span class="header-section-number">18.1.1</span> QQ plots vs.&nbsp;bivariate scatter plots</a></li>
  </ul></li>
  <li><a href="#what-can-we-learn-from-a-qq-plot" id="toc-what-can-we-learn-from-a-qq-plot" class="nav-link" data-scroll-target="#what-can-we-learn-from-a-qq-plot"><span class="header-section-number">18.2</span> What can we learn from a QQ plot?</a>
  <ul class="collapse">
  <li><a href="#additive-offset" id="toc-additive-offset" class="nav-link" data-scroll-target="#additive-offset"><span class="header-section-number">18.2.1</span> Additive offset</a></li>
  <li><a href="#multiplicative-offset" id="toc-multiplicative-offset" class="nav-link" data-scroll-target="#multiplicative-offset"><span class="header-section-number">18.2.2</span> Multiplicative offset</a></li>
  </ul></li>
  <li><a href="#additive-and-multiplicative-offsets" id="toc-additive-and-multiplicative-offsets" class="nav-link" data-scroll-target="#additive-and-multiplicative-offsets"><span class="header-section-number">18.3</span> Additive and multiplicative offsets</a></li>
  <li><a href="#the-tukey-mean-difference-plot" id="toc-the-tukey-mean-difference-plot" class="nav-link" data-scroll-target="#the-tukey-mean-difference-plot"><span class="header-section-number">18.4</span> The Tukey mean-difference plot</a></li>
  <li><a href="#generating-a-qq-plot-with-eda_qq" id="toc-generating-a-qq-plot-with-eda_qq" class="nav-link" data-scroll-target="#generating-a-qq-plot-with-eda_qq"><span class="header-section-number">18.5</span> Generating a QQ plot with <code>eda_qq</code></a></li>
  <li><a href="#generating-a-qq-plot-with-the-base-qqplot-function" id="toc-generating-a-qq-plot-with-the-base-qqplot-function" class="nav-link" data-scroll-target="#generating-a-qq-plot-with-the-base-qqplot-function"><span class="header-section-number">18.6</span> Generating a QQ plot with the base <code>qqplot</code> function</a></li>
  <li><a href="#generating-a-qq-plot-with-ggplot" id="toc-generating-a-qq-plot-with-ggplot" class="nav-link" data-scroll-target="#generating-a-qq-plot-with-ggplot"><span class="header-section-number">18.7</span> Generating a QQ plot with <code>ggplot</code></a></li>
  <li><a href="#is-the-relationship-between-tenor-and-bass-singers-additive-or-multiplicative" id="toc-is-the-relationship-between-tenor-and-bass-singers-additive-or-multiplicative" class="nav-link" data-scroll-target="#is-the-relationship-between-tenor-and-bass-singers-additive-or-multiplicative"><span class="header-section-number">18.8</span> Is the relationship between tenor and bass singers additive or multiplicative?</a></li>
  <li><a href="#comparing-multiple-batches-using-a-qq-plot-matrix" id="toc-comparing-multiple-batches-using-a-qq-plot-matrix" class="nav-link" data-scroll-target="#comparing-multiple-batches-using-a-qq-plot-matrix"><span class="header-section-number">18.9</span> Comparing multiple batches using a QQ plot matrix</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">18.10</span> Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./univariate_preamble.html">Univariate</a></li><li class="breadcrumb-item"><a href="./compare_batches.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">The Empirical QQ Plot</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">The Empirical QQ Plot</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="cell-output-display">
<table data-quarto-disable-processing="true" class="table" style="width: auto !important; ">
 <thead>
  <tr>
   <th style="text-align:left;color: rgba(85, 85, 85, 255) !important;background-color: rgba(221, 221, 221, 255) !important;text-align: center;border: 1px solid white !important;
             font-family: 'Source Code Pro', 'Open Sans';
             padding:1px !important;
             padding-left:4px !important;
             padding-right:4px !important;
             font-size: 0.8em;
             border-radius: 5px;"> dplyr </th>
   <th style="text-align:left;color: rgba(85, 85, 85, 255) !important;background-color: rgba(221, 221, 221, 255) !important;text-align: center;border: 1px solid white !important;
             font-family: 'Source Code Pro', 'Open Sans';
             padding:1px !important;
             padding-left:4px !important;
             padding-right:4px !important;
             font-size: 0.8em;
             border-radius: 5px;"> ggplot2 </th>
   <th style="text-align:left;color: rgba(85, 85, 85, 255) !important;background-color: rgba(221, 221, 221, 255) !important;text-align: center;border: 1px solid white !important;
             font-family: 'Source Code Pro', 'Open Sans';
             padding:1px !important;
             padding-left:4px !important;
             padding-right:4px !important;
             font-size: 0.8em;
             border-radius: 5px;"> tukeyedar </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;color: darkred !important;background-color: rgba(250, 232, 232, 255) !important;text-align: center;border: 1px solid white;
             font-family: 'Open Sans', Arial;
             padding:1px !important;
             padding-left:4px !important;
             padding-right:4px !important;
             font-size: 0.8em;
             border-radius: 5px;"> 1.2.0 </td>
   <td style="text-align:left;color: darkred !important;background-color: rgba(250, 232, 232, 255) !important;text-align: center;border: 1px solid white;
             font-family: 'Open Sans', Arial;
             padding:1px !important;
             padding-left:4px !important;
             padding-right:4px !important;
             font-size: 0.8em;
             border-radius: 5px;"> 4.0.2 </td>
   <td style="text-align:left;color: darkred !important;background-color: rgba(250, 232, 232, 255) !important;text-align: center;border: 1px solid white;
             font-family: 'Open Sans', Arial;
             padding:1px !important;
             padding-left:4px !important;
             padding-right:4px !important;
             font-size: 0.8em;
             border-radius: 5px;"> 0.5.0 </td>
  </tr>
</tbody>
</table>
</div>
</div>
<hr>
<p>In the previous chapter, we explored various plots used to visualize and understand the distribution of a single variable. However, we frequently seek to compare the distributions of <em>two or more</em> variables. For instance, we might want to compare the distribution of a contaminant in a polluted site to that of an unpolluted site. Additionally, we may wish to assess how well a variable’s distribution aligns with a theoretical one, a topic we’ll delve into in the next chapter.</p>
<p>While histograms and density plots can provide a general overview of distributions, their comparative power is limited. <strong>Empirical quantile-quantile plots</strong> (or <strong>QQ plot</strong> for short) offer a more precise and informative comparison by plotting the quantiles of one distribution against the quantiles of another. This allows us to identify systematic differences in shape, scale, and tail behavior, making QQ plots a powerful tool for understanding distributional relationships.</p>
<section id="the-empirical-quantile-quantile-qq-plot" class="level2" data-number="18.1">
<h2 data-number="18.1" class="anchored" data-anchor-id="the-empirical-quantile-quantile-qq-plot"><span class="header-section-number">18.1</span> The empirical quantile-quantile (QQ) plot</h2>
<p>An <strong>empirical quantile-quantile</strong> plot (or <strong>QQ plot</strong> for short) combines <a href="univariate_plots.html#quantile-plots">quantile functions</a> from two different batches of values by pairing their quantile values with their common <span class="math inline">\(f\)</span> fractions. The word <em>empirical</em> implies that we are comparing observational values. This serves to differentiate it from the <em>theoretical</em> QQ plot that will be covered in the next chapter.</p>
<p><img src="img/QQ_plot.png" class="img-fluid"></p>
<p>In the above figure, batches <code>a</code> and <code>b</code> have the same number of observations, 21 this example. As such, they have the same set of <span class="math inline">\(f\)</span>-values. If the number of observations in both batches are equal, then the plotting process is straightforward: both batches are sorted from smallest value to largest value, then they are paired up by their common <span class="math inline">\(f\)</span>-values generating the QQ plot shown on the right in the above figure. For example, for an <span class="math inline">\(f\)</span>-value of 0.5 (i.e.&nbsp;the median), batch <code>a</code> has a quantile value of 69 and batch <code>b</code> has a quantile value of 68. These values are paired up and assigned a single point in the QQ plot.</p>
<p>You’ll note the addition of a diagonal line to the plot. This line represents the part of the plot where <span class="math inline">\(x\)</span> = <span class="math inline">\(y\)</span>. If the quantiles for <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> are equal for a given <span class="math inline">\(f\)</span>-value, the point will fall on the <span class="math inline">\(x\)</span>=<span class="math inline">\(y\)</span> line. Points falling under the line indicate that the <span class="math inline">\(x\)</span> value is <em>larger</em> than the <span class="math inline">\(y\)</span> value for a given <span class="math inline">\(f\)</span>-value. Points falling above the line indicate that the <span class="math inline">\(x\)</span> value is <em>smaller</em> than the <span class="math inline">\(y\)</span> value for a given <span class="math inline">\(f\)</span>-value.</p>
<p>If there are ties in the quantile values, the QQ plot may not necessarily display the expected number of points. In the above example, there are 6 ties resulting in what appears to be just 15 points in the QQ plot when in fact, we are observing overlapping points. The above figure applies a transparency to the points. What may appear as a point with a darker shade of grey is actually overlapping points. For example, batch <code>a</code> has 7 observations associated with a value of 69. These 7 observations are paired with 7 observations in batch <code>b</code> that also have ties–these are 66, 67 and 68. This results in two overlapping points in the QQ plot where <code>a</code> has a value of 69 and <code>b</code> a value of 66, another two overlapping points where <code>a</code> has a value of 69 and <code>b</code> a value of 67, and three overlapping points where <code>a</code> has a value of 69 and <code>b</code> a value of 68.</p>
<p>If the two batches <strong>differ in size</strong> (i.e.&nbsp;have different number of observations), we won’t be able to match their sorted values from the outset because their <span class="math inline">\(f\)</span>-values will not match (recall from the previous chapter that the computed <span class="math inline">\(f\)</span>-value is a function of the number of observation in the batch).</p>
<p><img src="img/qq_plot_diff_lengths.png" class="img-fluid" width="700"></p>
<p>For example, in the above figure, you’ll note that batch <code>b</code> has a value associated with an <span class="math inline">\(f\)</span>-value of <code>0.44</code>, however, there is no value associated with an <span class="math inline">\(f\)</span>-value of <code>0.44</code> in batch <code>a</code>. Batch <code>a</code> consists of 9 observations while batch <code>b</code> consists of just 8 observations. This results in an <span class="math inline">\(f\)</span>-value that ranges from 0.056 to 0.0944 for batch <code>a</code> and a range of 0.063 to 0.938 for batch <code>b</code>.</p>
<p>To overcome the problem of batch size mismatch, we limit the number of points in the QQ plot to the number of values associated with the <em>smallest</em> sized batch (8 in this working example). This requires that we find the <code>a</code> quantiles for the set of <span class="math inline">\(f\)</span>-values associated with batch <code>b</code> via the <a href="http://localhost:4724/univariate_plots.html#interpolating-a-quantile"><em>interpolation techniques</em> covered in the previous chapter</a>. This results in the <span class="math inline">\(f\)</span>-quantile plot shown on the right hand side of the figure. The interpolated batch is labelled <code>a*</code> that now has the same number of observations as <code>b</code> thus the same set of <span class="math inline">\(f\)</span>-values.</p>
<p>It’s worth recalling from chapter 16 that the quantile function is, as its name implies, a function. As such, a batch of continuous values whose quantile function we are defining can take on any values within the range defined by the function. We choose to have the largest batch of values downsized to the smallest batch so as to avoid issues of extrapolation at the tail ends of the distribution–an issue we would have encountered had we expanded the smaller batch of values to match the number of observations in the larger batch.</p>
<section id="qq-plots-vs.-bivariate-scatter-plots" class="level3" data-number="18.1.1">
<h3 data-number="18.1.1" class="anchored" data-anchor-id="qq-plots-vs.-bivariate-scatter-plots"><span class="header-section-number">18.1.1</span> QQ plots vs.&nbsp;bivariate scatter plots</h3>
<p>It’s important to note the difference between a quantile-quantile plot and a <a href="https://en.wikipedia.org/wiki/Scatter_plot"><em>bivariate</em> scatter plot</a>. With the latter, the pairing of values between variables is explicitly defined (for example average male and female income values may be paired by county) whereas in a QQ plot, the pairing is driven by the matching <span class="math inline">\(f\)</span> values.</p>
</section>
</section>
<section id="what-can-we-learn-from-a-qq-plot" class="level2" data-number="18.2">
<h2 data-number="18.2" class="anchored" data-anchor-id="what-can-we-learn-from-a-qq-plot"><span class="header-section-number">18.2</span> What can we learn from a QQ plot?</h2>
<p>To understand what a QQ plot can tell us about the relationship between two distributions, we need to first explore key ways in which distributions may differ.</p>
<p>The <span class="math inline">\(x=y\)</span> diagonal line in the QQ plot represents the location on the plot where the quantiles between both batches are equal. If all points fall on this line, we say that the shape of the distributions between both batches are equal. Such a scenario is rare with observational data. Our interest is in understanding how the batches differ. Comparing the point pattern in the QQ plot to the <span class="math inline">\(x=y\)</span> line can tell us a fair amount about the differences in distributions.</p>
<p>In what follows, we explore the <strong>additive</strong> and <strong>multiplicative</strong> ways batches can differ in shape.</p>
<section id="additive-offset" class="level3" data-number="18.2.1">
<h3 data-number="18.2.1" class="anchored" data-anchor-id="additive-offset"><span class="header-section-number">18.2.1</span> Additive offset</h3>
<p>A valuable by-product of an empirical QQ plot is the mathematical relationship between the batches of values. If the distributions are identical (i.e.&nbsp;all the points of a QQ plot fall on the <span class="math inline">\(x=y\)</span> line) then we could characterize the relationship as <code>batch1 = batch2</code>.</p>
<p>If, on the other hand, the points follow a <em>pattern</em> mimicking a line parallel to the <span class="math inline">\(x=y\)</span> line as in the following plot, then we say that there is an <strong>additive shift</strong> between <code>batch1</code> and <code>batch2</code>. An additive shift between batches results in an offset in distributions when viewed through the lens of a density plot (see plot on the right). Note that the <em>shape</em> of the distributions remain comparable dispite the additive offset.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="compare_batches_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The offset from the <span class="math inline">\(x=y\)</span> line can usually be eyeballed in the plot. If we measure this offset along the y-axis of our working example, we get an offset of around 2 units suggesting a relationship in the form of <code>batch2 =  batch1 + 2</code>. To confirm this, we can add <code>2</code> to <code>batch 1</code> and generate a new QQ plot as follows:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="compare_batches_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Adding 2 to <code>batch1</code> lines the points up along the <span class="math inline">\(x=y\)</span> line confirming our estimate additive offset of 2 units.</p>
<p>An additive offset offers a succinct way in characterizing the differences in shape. It implies that across <em>all</em> quantiles (this includes the median and upper and lower quartiles), <code>a</code> is generally 2 units greater than <code>b</code>.</p>
</section>
<section id="multiplicative-offset" class="level3" data-number="18.2.2">
<h3 data-number="18.2.2" class="anchored" data-anchor-id="multiplicative-offset"><span class="header-section-number">18.2.2</span> Multiplicative offset</h3>
<p>When the points follow a line at an angle to the <span class="math inline">\(x=y\)</span> line, then we say that there is a <strong>multiplicative shift</strong> between the batches. When viewed through the lens of a density plot, the multiplicative shift between the batches results in a change in shapes with one batch’s density being shorter and wider (<code>batch2</code> in this example) than that of the other batch (<code>batch1</code> in this example).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="compare_batches_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The multiplier can be gleaned from the graph by estimating the slope defining the point pattern. For example, a multiplier of 2 seems to do a good job in aligning the QQ points along the <span class="math inline">\(x=y\)</span> line. We can thus define the relationship as being <code>batch2 = batch1 * 2</code>. A QQ plot of <code>batch2</code> vs <code>batch1 * 2</code> is shown next.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="compare_batches_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Notice in the density plot how applying a multiplier not only renders comparable shapes for both batches, but it also corrects the offset observed between both density distributions in the previous figure.</p>
</section>
</section>
<section id="additive-and-multiplicative-offsets" class="level2" data-number="18.3">
<h2 data-number="18.3" class="anchored" data-anchor-id="additive-and-multiplicative-offsets"><span class="header-section-number">18.3</span> Additive and multiplicative offsets</h2>
<p>Sometimes, you might encounter a relationship that is both additive <em>and</em> multiplicative in which case you should first resolve the multiplicative part of the pattern until the points are close to being parallel with the <span class="math inline">\(x=y\)</span> line. Once the multiplicative component is corrected for, you then resolve the additive offset.</p>
<p>Here’s an example of a pair of distributions exhibiting both types of offset.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="compare_batches_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We first decompose the offset into its multiplicative component. After some trial and error, a <code>batch1</code> multiplier of around 1.5 seems to do a good job in rendering a point pattern parallel to the <span class="math inline">\(x=y\)</span> line.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="compare_batches_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>With the multiplicative offset identified, we tackle its additive component. When measured along the y-axis we estimate an offset of about four units:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="compare_batches_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The relationship between both batches can thus be mathematically defined by <code>batch2 = batch1 * 1.5 + 4</code>.</p>
</section>
<section id="the-tukey-mean-difference-plot" class="level2" data-number="18.4">
<h2 data-number="18.4" class="anchored" data-anchor-id="the-tukey-mean-difference-plot"><span class="header-section-number">18.4</span> The Tukey mean-difference plot</h2>
<p>Our eyes are better suited at judging deviations from a horizontal line than from a 45° line. It can therefore be helpful to visually “rotate” the QQ plot 45° so as to render what was a diagonal line a horizontal one. To tackle this requires that we subtract the x-value (<code>a</code>) from the y-value (<code>b</code>), and compare this difference to the mean of the two values. The resulting <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> values are expressed as:</p>
<p><span class="math display">\[
Y = y - x
\]</span> <span class="math display">\[
X = \frac{x + y}{2}
\]</span></p>
<p>While the axes values change, the layout of the points relative to the line changes very little. Such a plot was first introduced by John Tukey–hence his surname in the plot name. However, you are more likely to see the plot referenced simply as the <em>mean-difference</em> plot.</p>
<p>A comparison of the QQ plot (left) and the mean-difference plot (right) are shown next.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="compare_batches_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The <span class="math inline">\(x=y\)</span> line in the QQ plot becomes the <span class="math inline">\(y=0\)</span> line. Deviations from this line, measured along the <span class="math inline">\(y\)</span>-axis represent the additive offset observed between batches. To account for the multiplicative offset, the slope defined by the point pattern in the mean-difference plot must be transformed before applying it to the QQ plot, as follows:</p>
<p><span class="math display">\[
m = \frac{2 + m'}{2 - m'}
\quad
\begin{cases}
    m' = 0, &amp; m = 1 \\
    m' = 2, &amp; m = \frac{4}{0} \quad \text{(undefined, vertical line in QQ plot)} \\
    m' \to \infty, &amp; m \approx -1
\end{cases}
\]</span></p>
<p>where <span class="math inline">\(m'\)</span> is the slope defined by the point pattern in the mean-difference plot and <span class="math inline">\(m\)</span> is the corresponding slope in the QQ plot.</p>
</section>
<section id="generating-a-qq-plot-with-eda_qq" class="level2" data-number="18.5">
<h2 data-number="18.5" class="anchored" data-anchor-id="generating-a-qq-plot-with-eda_qq"><span class="header-section-number">18.5</span> Generating a QQ plot with <code>eda_qq</code></h2>
<p>In the working example that follows, we will compare the distribution between two singer groups: The <code>tenor1</code> group and the <code>bass2</code> group from the <code>singer</code> dataset found in the <code>lattice</code> package.</p>
<p>First, we extract the height values for both singer groups from the <code>singer</code> dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>df  <span class="ot">&lt;-</span> lattice<span class="sc">::</span>singer</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>Bass2  <span class="ot">&lt;-</span> <span class="fu">filter</span>(df, voice.part <span class="sc">==</span> <span class="st">"Bass 2"</span>)  <span class="sc">%&gt;%</span> <span class="fu">pull</span>(height)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>Tenor1 <span class="ot">&lt;-</span> <span class="fu">filter</span>(df, voice.part <span class="sc">==</span> <span class="st">"Tenor 1"</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(height)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We will make use of the <code>eda_qq()</code> function found in the <code>tukeyedar</code> package. The function can take, as input, two vectors (each representing the two batches) or, it can take as input a dataframe with a variable column and a category column. In the example that follows we will pass it the two singer height vectors created in the previous code chunk.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r eda code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eda_qq</span>(Tenor1, Bass2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="compare_batches_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="288"></p>
</figure>
</div>
</div>
</div>
<p>By default, the plot includes the following features:</p>
<ul>
<li>Shaded regions representing each batch’s mid 75% range.</li>
<li>Dashed lines inside the shaded boxes representing each batch’s median values.</li>
<li>The power transformation applied to both batches shown in the upper right-hand corner of the plot. Power transformations will be covered in later chapters.</li>
</ul>
<p>Note that if the two batches differ in size, <code>eda_qq</code> will interpolate the larger batch to match the number of observations in the smaller batch.</p>
<p>If you want a plain vanilla QQ plot, simply add the arguments <code>med = FALSE</code>, <code>q = FALSE</code> and <code>show.par = FALSE</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r eda code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eda_qq</span>(Tenor1, Bass2, <span class="at">med =</span> <span class="cn">FALSE</span>, <span class="at">q =</span> <span class="cn">FALSE</span>, <span class="at">show.par =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="compare_batches_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="288"></p>
</figure>
</div>
</div>
</div>
<p>To create a Tukey mean-difference plot, simply add the argument <code>md = TRUE</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r eda code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eda_qq</span>(Tenor1, Bass2, <span class="at">med =</span> <span class="cn">FALSE</span>, <span class="at">q =</span> <span class="cn">FALSE</span>, <span class="at">show.par =</span> <span class="cn">FALSE</span>, <span class="at">md =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="compare_batches_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="288"></p>
</figure>
</div>
</div>
</div>
<p>The <code>eda_qq</code> function makes use of the <code>quantile</code> function behind the scenes. It adopts the <code>qtype = 5</code> option when computing the <span class="math inline">\(f\)</span>-value. You can change the type via the <code>q.type</code> argument in <code>eda_qq</code>.</p>
<p>To learn more about the <code>eda_qq</code> function, see <a href="https://mgimond.github.io/tukeyedar/articles/qq.html">here</a>.</p>
</section>
<section id="generating-a-qq-plot-with-the-base-qqplot-function" class="level2" data-number="18.6">
<h2 data-number="18.6" class="anchored" data-anchor-id="generating-a-qq-plot-with-the-base-qqplot-function"><span class="header-section-number">18.6</span> Generating a QQ plot with the base <code>qqplot</code> function</h2>
<p>Base R has a QQ plot function called <code>qqplot()</code>. This function will, however, not add the <span class="math inline">\(x=y\)</span> line requiring that we follow up with a call to <code>abline(0,1)</code>. For example:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqplot</span>(Tenor1, Bass2)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="compare_batches_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="288"></p>
</figure>
</div>
</div>
</div>
<p>The <code>qqplot</code> function will default to <code>qtype = 7</code> in the <code>quantile</code> function.</p>
<p>You’ll note that the x and y axis ranges will not necessarily match (this explains why the <span class="math inline">\(x=y\)</span> line does not connect the two corners of the plot). You can equalize the axes ranges by adding the <code>xlim</code> and <code>ylim</code> arguments. For example:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>rng <span class="ot">&lt;-</span> <span class="fu">range</span>(Tenor1, Bass2)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqplot</span>(Tenor1, Bass2, <span class="at">xlim =</span> rng, <span class="at">ylim =</span> rng, <span class="at">asp =</span> <span class="dv">1</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="compare_batches_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="288"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="generating-a-qq-plot-with-ggplot" class="level2" data-number="18.7">
<h2 data-number="18.7" class="anchored" data-anchor-id="generating-a-qq-plot-with-ggplot"><span class="header-section-number">18.7</span> Generating a QQ plot with <code>ggplot</code></h2>
<p><code>ggplot</code> does not have a built-in empirical QQ plot function. Instead, the data need to be prepped beforehand. This includes any interpolation that may be required if the batch sizes do not match.</p>
<p>The easiest way to ensure that the batches match in size is to use the <code>qqplot()</code> function with the argument <code>plot.it = FALSE</code>. The output is a list of the two batches matching in size. The <code>qqplot</code> function will name the output columns <code>x</code> and <code>y.</code> We therefore will need to reassign the voice part names to the dataframe columns in the same order that they were passed to in the <code>qqplot</code> function.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>qq.out <span class="ot">&lt;-</span> <span class="fu">qqplot</span>(<span class="at">x=</span>Tenor1, <span class="at">y=</span>Bass2, <span class="at">plot.it=</span><span class="cn">FALSE</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>qq.out <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(qq.out)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(qq.out) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Tenor1"</span>, <span class="st">"Bass2"</span>)  <span class="co"># Add batch names to output</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We can now generate the QQ plot using <code>ggplot</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the x and y limits</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>xylim <span class="ot">&lt;-</span> <span class="fu">range</span>( <span class="fu">c</span>(qq.out<span class="sc">$</span>Tenor1, qq.out<span class="sc">$</span>Bass2) )</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate the QQ plot</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(qq.out, <span class="fu">aes</span>( <span class="at">x=</span> Tenor1, <span class="at">y =</span> Bass2)) <span class="sc">+</span> </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>               <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>               <span class="fu">geom_abline</span>( <span class="at">intercept=</span><span class="dv">0</span>, <span class="at">slope=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>               <span class="fu">coord_fixed</span>(<span class="at">ratio =</span> <span class="dv">1</span>, <span class="at">xlim=</span>xylim, <span class="at">ylim =</span> xylim) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="compare_batches_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="288"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="is-the-relationship-between-tenor-and-bass-singers-additive-or-multiplicative" class="level2" data-number="18.8">
<h2 data-number="18.8" class="anchored" data-anchor-id="is-the-relationship-between-tenor-and-bass-singers-additive-or-multiplicative"><span class="header-section-number">18.8</span> Is the relationship between tenor and bass singers additive or multiplicative?</h2>
<p>When measured along the y-axis, an additive shift of about 2.5 inches is apparent in the QQ plot, but a multiplicative shift not so much. To check, we’ll add 2.5 to the <code>Tenor1</code> values. This can be done in the <code>eda_qq</code> function with the <code>fx</code> argument. We’ll enable the <code>show.par</code> argument given that the expression applied to the x variable will be displayed in the upper right-hand corner of the plot along with the power transformation. Having this extra bit of information on the plot will help remind us that the plot is that of a modified set of x values.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r eda code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eda_qq</span>(Tenor1, Bass2, <span class="at">med =</span> <span class="cn">FALSE</span>, <span class="at">q =</span> <span class="cn">FALSE</span>, <span class="at">fx =</span> <span class="st">"x + 2.5"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="compare_batches_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="288"></p>
</figure>
</div>
</div>
</div>
<p>Adding <code>2.5</code> inches to the <code>Tenor</code> group helps align the points along the <span class="math inline">\(x=y\)</span> line. There is no indication of a multiplicative offset between the distributions. The outliers in the upper right-hand corner of the plot should not mislead us into assuming that a multiplicative offset is warranted here.</p>
<p>If you want to apply an offset to the y-axis values, use the <code>fy</code> argument. Recall from basic algebra that <span class="math inline">\(y = ax + b \Leftrightarrow x = (y - b) / a\)</span>. Don’t forget to reference the <code>y</code> variable instead of the <code>x</code> variable in the formula.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r eda code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eda_qq</span>(Tenor1, Bass2, <span class="at">med =</span> <span class="cn">FALSE</span>, <span class="at">q =</span> <span class="cn">FALSE</span>, <span class="at">fy =</span> <span class="st">"y - 2.5"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="compare_batches_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="240"></p>
</figure>
</div>
</div>
</div>
<p>The point pattern is identical to that in the previous plot. The one notable difference is the range of x and y values. This is to be expected since the y values are now being modified instead of the x values.</p>
<p>You’ll note that the <code>eda_qq</code> function returns a “suggested” offset in the console. This suggested offset is computed from the raw data, i.e.&nbsp;it ignores any offsets specified in the <code>fx</code> or <code>fy</code> arguments. Note that the proposed offset may not always faithfully capture the nature of the pattern in the QQ plot, hence why it’s always good practice to use graphical techniques to help fine tune the relationship between variables.</p>
<p>For example, you may have noticed the following output in the console when running the above code chunks:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Suggested offsets:y = x * 0.8571 + (12.4286)"</code></pre>
</div>
</div>
<p>Applying the suggested offset to the x-axis variable gives us the following plot:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r eda code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eda_qq</span>(Tenor1, Bass2, <span class="at">med =</span> <span class="cn">FALSE</span>, <span class="at">q =</span> <span class="cn">FALSE</span>, <span class="at">fx =</span> <span class="st">" x * 0.8571 + 12.4286 "</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="compare_batches_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="240"></p>
</figure>
</div>
</div>
</div>
<p>This seems to improve very little over the simpler <code>x + 2</code> offset expression. We’ll therefore stick with the simpler <code>Bass2 = Tenor1 + 2</code> description of the comparative distributions given that it’s always best to seek a parsimonious relationship between batches when possible.</p>
</section>
<section id="comparing-multiple-batches-using-a-qq-plot-matrix" class="level2" data-number="18.9">
<h2 data-number="18.9" class="anchored" data-anchor-id="comparing-multiple-batches-using-a-qq-plot-matrix"><span class="header-section-number">18.9</span> Comparing multiple batches using a QQ plot matrix</h2>
<p>Some analytical workflows may require that more than one pair of distributions be compared. For example, we might want to assess if the <code>height</code> distributions across all singer groups (<code>voice.part</code>) differ additively and not multiplicatively. The <code>singer</code> dataset consists of eight <code>voice.part</code> groups. This requires making <span class="math inline">\(8 * (8-1) /2 = 28\)</span> comparisons, something that is best done by generating a QQ plot matrix. We’ll make use of <code>tukeyedar</code>’s <code>eda_qqmat()</code> function. It accepts most of the same arguments used in the <code>eda_qq()</code> function, however, it will only accept a dataframe with one column storing the continuous variable and the other column storing the categorical variable.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r eda code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eda_qqmat</span>(df, height, voice.part, <span class="at">size =</span> <span class="fl">0.7</span>, <span class="at">diag =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="compare_batches_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>With few exceptions, the singer height distributions differ mostly by an additive offset given that most points are parallel to the <span class="math inline">\(x=y\)</span> line. There is one notable exception: the <code>Tenor 1</code> and <code>Tenor 2</code> QQ plot which seems to show a prominent multiplicative (and possibly additive) offset. We can explore this pair in greater detail using the <code>eda_qq()</code> function.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r eda code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>Tenor1 <span class="ot">&lt;-</span> <span class="fu">filter</span>(df, voice.part <span class="sc">==</span> <span class="st">"Tenor 1"</span>) <span class="sc">%&gt;%</span>  <span class="fu">pull</span>(height)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>Tenor2 <span class="ot">&lt;-</span> <span class="fu">filter</span>(df, voice.part <span class="sc">==</span> <span class="st">"Tenor 2"</span>) <span class="sc">%&gt;%</span>  <span class="fu">pull</span>(height)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">eda_qq</span>(Tenor2, Tenor1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Suggested offsets:y = x * 1.4615 + (-32.8462)"</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="compare_batches_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="240"></p>
</figure>
</div>
</div>
</div>
<p>Before attempting to quantify the multiplicative and additive offsets differentiating both distributions, its worth noting the difference in ranges of values covered by singer groups. in the above plot, the grey region shows the inner 75% of values for both groups. Note how the shaded region region for the <code>Tenor2</code> group covers a narrower range of height values than the <code>Tenor1</code> group. This suggests more variability in the <code>Tenor1</code> height values than in the <code>Tenor2</code> height values. This difference in distribution “width” helps explain the multiplicative offset oberved in the QQ plot.</p>
<p>The console output suggests an offset of <code>x * 1.46 -32.8</code>. We can first try a multiplier of <code>1.5</code> to see if it renders a pattern of points parallel to the <span class="math inline">\(x=y\)</span> line. However, doing so will generate a QQ plot that will make it difficult to determine if the point pattern is indeed parallel to the <span class="math inline">\(x=y\)</span> line (the points end up being squeezed in the bottom corner of the QQ plot). This distribution comparison may be a good candidate for a Tukey mean-difference plot. Both plots are shown side-by side in the following figure.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r eda code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eda_qq</span>(Tenor2, Tenor1, <span class="at">fx =</span> <span class="st">"x * 1.5"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">eda_qq</span>(Tenor2, Tenor1, <span class="at">fx =</span> <span class="st">"x * 1.5"</span>, <span class="at">md =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="compare_batches_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>The mean-difference plot makes it far easier to gauge how well the multiplier has helped render the points parallel to the <span class="math inline">\(y=0\)</span> (i.e.&nbsp;what is the <span class="math inline">\(x=y\)</span> line in the QQ plot). The mean-difference plot also helps us gauge the additive offset once the multiplicative offset is identified. Here, the additive offset seems to be around <code>-36</code> (some trial and error may be needed to get to that number).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r eda code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eda_qq</span>(Tenor2, Tenor1, <span class="at">fx =</span> <span class="st">"x * 1.5 - 36"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">eda_qq</span>(Tenor2, Tenor1, <span class="at">fx =</span> <span class="st">"x * 1.5 - 36"</span>, <span class="at">md =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="compare_batches_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>The multiplicative and additive offsets could benefit from some fine-tuning (the points appear to be at a slight angle to the reference line in both plots). How much time you choose to invest in fine-tuning the parameters will depend on the level of accuracy needed in quantifying the differences in distribution between both batch of values.</p>
</section>
<section id="summary" class="level2" data-number="18.10">
<h2 data-number="18.10" class="anchored" data-anchor-id="summary"><span class="header-section-number">18.10</span> Summary</h2>
<p>In this chapter, you learned how to compare two or more batches of data using empirical quantile–quantile (QQ) plots. Unlike side-by-side boxplots or density overlays, QQ plots allow for direct visual comparison of quantiles, making it easier to detect differences in location, spread, and shape. This approach emphasizes the importance of comparing distributions holistically rather than relying solely on summary statistics.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./univariate_plots.html" class="pagination-link" aria-label="Visualizing Univariate Distributions">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Visualizing Univariate Distributions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./theoretical_qq.html" class="pagination-link" aria-label="The Theoretical QQ Plot">
        <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">The Theoretical QQ Plot</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Manny Gimond, Creative Commons License <a href="https://creativecommons.org/licenses/by-nc/4.0/"><img src="https://i.creativecommons.org/l/by-nc/4.0/80x15.png" class="img-fluid"></a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>