<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Exploratory Data Analysis in R - 28&nbsp; Analyzing two-way tables: The median polish</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./rmarkdown.html" rel="next">
<link href="./discontinuity.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-CJW3PSXZC2"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-CJW3PSXZC2', { 'anonymize_ip': true});
</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="libs/style.css">
</head>

<body class="nav-sidebar docked">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./two_way.html">Two-way tables</a></li><li class="breadcrumb-item"><a href="./two_way.html"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Analyzing two-way tables: The median polish</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./"></a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Intro</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">EDA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./The_R_environment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The R and RStudio Environments</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Data manipulation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_objects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Object Type and Structure</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./read_write_files.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Reading and Writing Data Files</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./date_objects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Working with Dates</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./strings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Working with string objects</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./boolean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Relational and boolean operations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./subset_base.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Manipulating data tables using base functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Manipulating data tables with <code>dplyr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./group_by.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Grouping and summarizing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tidyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Tidying/reshaping tables with <code>tidyr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./joins.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Joining Data Tables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Plots</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./base_plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Base plotting environment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lattice_plot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Lattice plotting environment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ggplot2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">ggplot2 plotting environment</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Univariate</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./univariate_plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Visualizing univariate distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./compare_batches.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Comparing distributions: The q-q plot</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./theoretical_qq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">The theoretical q-q plot</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rf.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Fits and residuals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sl_plot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Spread-level plots</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./re_express.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Re-expressing values</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./letter_values.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Letter value summaries</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./case_study.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">A working example: t-tests and re-expression</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Bivariate</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bivariate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Fits and residuals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resistant_lines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Resistant lines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">The third R of EDA: Residuals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discontinuity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Slicing data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Two-way tables</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./two_way.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Analyzing two-way tables: The median polish</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
 <span class="menu-text">Miscellaneous</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rmarkdown.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">R markdown document</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./spatial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Mapping variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Data used in ES218</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">28.1</span> Introduction</a></li>
  <li><a href="#anatomy-of-a-two-way-table" id="toc-anatomy-of-a-two-way-table" class="nav-link" data-scroll-target="#anatomy-of-a-two-way-table"><span class="header-section-number">28.2</span> Anatomy of a two-way table</a></li>
  <li><a href="#analysis-workflow" id="toc-analysis-workflow" class="nav-link" data-scroll-target="#analysis-workflow"><span class="header-section-number">28.3</span> Analysis workflow</a>
  <ul class="collapse">
  <li><a href="#visualizing-the-data" id="toc-visualizing-the-data" class="nav-link" data-scroll-target="#visualizing-the-data"><span class="header-section-number">28.3.1</span> Visualizing the data</a></li>
  <li><a href="#median-polish" id="toc-median-polish" class="nav-link" data-scroll-target="#median-polish"><span class="header-section-number">28.3.2</span> Median polish</a></li>
  <li><a href="#interpreting-the-median-polish" id="toc-interpreting-the-median-polish" class="nav-link" data-scroll-target="#interpreting-the-median-polish"><span class="header-section-number">28.3.3</span> Interpreting the median polish</a></li>
  <li><a href="#test-for-non-additivity" id="toc-test-for-non-additivity" class="nav-link" data-scroll-target="#test-for-non-additivity"><span class="header-section-number">28.3.4</span> Test for non-additivity</a></li>
  </ul></li>
  <li><a href="#implementing-the-median-polish-in-r" id="toc-implementing-the-median-polish-in-r" class="nav-link" data-scroll-target="#implementing-the-median-polish-in-r"><span class="header-section-number">28.4</span> Implementing the median polish in R</a>
  <ul class="collapse">
  <li><a href="#using-base-rs-medpolish" id="toc-using-base-rs-medpolish" class="nav-link" data-scroll-target="#using-base-rs-medpolish"><span class="header-section-number">28.4.1</span> Using base R’s <code>medpolish</code></a></li>
  <li><a href="#using-eda_pol" id="toc-using-eda_pol" class="nav-link" data-scroll-target="#using-eda_pol"><span class="header-section-number">28.4.2</span> Using <code>eda_pol</code></a></li>
  </ul></li>
  <li><a href="#what-if-we-use-the-mean-instead-of-the-median" id="toc-what-if-we-use-the-mean-instead-of-the-median" class="nav-link" data-scroll-target="#what-if-we-use-the-mean-instead-of-the-median"><span class="header-section-number">28.5</span> What if we use the mean instead of the median?</a>
  <ul class="collapse">
  <li><a href="#two-way-anova" id="toc-two-way-anova" class="nav-link" data-scroll-target="#two-way-anova"><span class="header-section-number">28.5.1</span> Two-way ANOVA</a></li>
  <li><a href="#visualizing-a-two-way-anova-as-a-table" id="toc-visualizing-a-two-way-anova-as-a-table" class="nav-link" data-scroll-target="#visualizing-a-two-way-anova-as-a-table"><span class="header-section-number">28.5.2</span> Visualizing a two-way ANOVA as a table</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">28.6</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Analyzing two-way tables: The median polish</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell" data-hash="two_way_cache/html/unnamed-chunk-2_d6b817bd2dc7f751b645b175972dbeb2">
<div class="cell-output-display">

<table data-quarto-disable-processing="true" class="table" style="width: auto !important; ">
 <thead>
  <tr>
   <th style="text-align:left;color: rgba(85, 85, 85, 255) !important;background-color: rgba(221, 221, 221, 255) !important;text-align: center;border: 1px solid white !important;
             font-family: 'Source Code Pro', 'Open Sans';
             padding:1px !important;
             padding-left:4px !important;
             padding-right:4px !important;
             font-size: 0.8em;
             border-radius: 5px;"> dplyr </th>
   <th style="text-align:left;color: rgba(85, 85, 85, 255) !important;background-color: rgba(221, 221, 221, 255) !important;text-align: center;border: 1px solid white !important;
             font-family: 'Source Code Pro', 'Open Sans';
             padding:1px !important;
             padding-left:4px !important;
             padding-right:4px !important;
             font-size: 0.8em;
             border-radius: 5px;"> tidyr </th>
   <th style="text-align:left;color: rgba(85, 85, 85, 255) !important;background-color: rgba(221, 221, 221, 255) !important;text-align: center;border: 1px solid white !important;
             font-family: 'Source Code Pro', 'Open Sans';
             padding:1px !important;
             padding-left:4px !important;
             padding-right:4px !important;
             font-size: 0.8em;
             border-radius: 5px;"> tukeyedar </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;color: darkred !important;background-color: rgba(250, 232, 232, 255) !important;text-align: center;border: 1px solid white;
             font-family: 'Open Sans', Arial;
             padding:1px !important;
             padding-left:4px !important;
             padding-right:4px !important;
             font-size: 0.8em;
             border-radius: 5px;"> 1.1.4 </td>
   <td style="text-align:left;color: darkred !important;background-color: rgba(250, 232, 232, 255) !important;text-align: center;border: 1px solid white;
             font-family: 'Open Sans', Arial;
             padding:1px !important;
             padding-left:4px !important;
             padding-right:4px !important;
             font-size: 0.8em;
             border-radius: 5px;"> 1.3.1 </td>
   <td style="text-align:left;color: darkred !important;background-color: rgba(250, 232, 232, 255) !important;text-align: center;border: 1px solid white;
             font-family: 'Open Sans', Arial;
             padding:1px !important;
             padding-left:4px !important;
             padding-right:4px !important;
             font-size: 0.8em;
             border-radius: 5px;"> 0.2.1 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<section id="introduction" class="level2" data-number="28.1">
<h2 data-number="28.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">28.1</span> Introduction</h2>
<p>Before tackling two-way tables, let’s explore a simpler one-way table. The following dataset shows mean annual income by occupation for the year 2014 (<em>src: <a href="http://www.bls.gov/oes/#tables">Bureau of Labor Statistics</a></em>)</p>
<div class="cell" data-hash="two_way_cache/html/unnamed-chunk-3_bb5971ce07d8d8c0b8943589b38c4d73">

<!-- html table generated in R 4.3.2 by xtable 1.8-4 package -->
<!-- Mon Feb  5 09:05:50 2024 -->

<table border="1">
<tbody><tr>
<th>
</th>
<th>
Income
</th>
</tr>
<tr>
<td align="right">
Architecture and Engineering
</td>
<td align="right">
112490
</td>
</tr>
<tr>
<td align="right">
Arts, Design, Entertainment, Sports, and Media
</td>
<td align="right">
72410
</td>
</tr>
<tr>
<td align="right">
Building and Grounds Cleaning and Maintenance
</td>
<td align="right">
83970
</td>
</tr>
<tr>
<td align="right">
Business and Financial Operations
</td>
<td align="right">
81520
</td>
</tr>
<tr>
<td align="right">
Community and Social Service
</td>
<td align="right">
70070
</td>
</tr>
<tr>
<td align="right">
Computer and Mathematical
</td>
<td align="right">
45310
</td>
</tr>
<tr>
<td align="right">
Construction and Extraction
</td>
<td align="right">
101110
</td>
</tr>
<tr>
<td align="right">
Education, Training, and Library
</td>
<td align="right">
52210
</td>
</tr>
<tr>
<td align="right">
Farming, Fishing, and Forestry
</td>
<td align="right">
55790
</td>
</tr>
<tr>
<td align="right">
Food Preparation and Serving Related
</td>
<td align="right">
76010
</td>
</tr>
<tr>
<td align="right">
Healthcare Practitioners and Technical
</td>
<td align="right">
28820
</td>
</tr>
<tr>
<td align="right">
Healthcare Support
</td>
<td align="right">
43980
</td>
</tr>
<tr>
<td align="right">
Installation, Maintenance, and Repair
</td>
<td align="right">
21980
</td>
</tr>
<tr>
<td align="right">
Legal
</td>
<td align="right">
26370
</td>
</tr>
<tr>
<td align="right">
Life, Physical, and Social Science
</td>
<td align="right">
24980
</td>
</tr>
<tr>
<td align="right">
Management
</td>
<td align="right">
38660
</td>
</tr>
<tr>
<td align="right">
Office and Administrative Support
</td>
<td align="right">
35530
</td>
</tr>
<tr>
<td align="right">
Personal Care and Service
</td>
<td align="right">
25160
</td>
</tr>
<tr>
<td align="right">
Production
</td>
<td align="right">
46600
</td>
</tr>
<tr>
<td align="right">
Protective Service
</td>
<td align="right">
45220
</td>
</tr>
<tr>
<td align="right">
Sales and Related
</td>
<td align="right">
35490
</td>
</tr>
<tr>
<td align="right">
Transportation and Material Moving
</td>
<td align="right">
34460
</td>
</tr>

</tbody></table>
</div>
<p>So, what can we glean from this dataset other than the raw values associated with each occupation type? For starters, we may be interested in coming up with a summary of income values such as the median, or $45265 in our working example. This is a single value that can be used to characterize the overall income value. However, the income values in our batch are not all equal to $45265–they vary above or below this median value. A good way to measure the variability about the median is to subtract the median income value from each occupation income value. We can do this in a table, but will choose a dotplot chart instead to facilitate comparison.</p>
<div class="cell" data-small.mar="true" data-hash="two_way_cache/html/unnamed-chunk-4_934225ecb0f6ab68fb9c7c5da7f21f3a">
<div class="cell-output-display">
<p><img src="two_way_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="576"></p>
</div>
</div>
<p>We have separated the income values into two parts: an <strong>overall</strong> value and the difference between each value and the overall–i.e.&nbsp;the <strong>residuals</strong>. This can be written in the following algebraic form:</p>
<p><span class="math display">\[
Income_{Occupation} = Income_{median} + Income_{residual}
\]</span></p>
<p>For example, ‘Healthcare Support’ average income of $43980 can be separated into the median, $45265, and its residual, $-1285.</p>
<p>So, in addition to gleaning a median income value from this batch of values, we have also devised a way to facilitate the comparison of the income values to one another. Alternatively, we could have assigned colors to each cell of the table reflecting their values <em>relative</em> to the overall median.</p>
<div class="cell" data-small.mar="true" data-hash="two_way_cache/html/unnamed-chunk-5_4a4743b3e9246aea859a9b3f2be216dc">
<div class="cell-output-display">
<p><img src="two_way_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="384"></p>
</div>
</div>
<p>The income value can be thought of as the <strong>response</strong> to the occupation type (also known as a <strong>factor</strong>). In other words, the factor determines the value in our table. We can re-write the last equation in a more formal way:</p>
<p><span class="math display">\[
y_{i} = \mu + \epsilon_i
\]</span></p>
<p>where <span class="math inline">\(y_{i}\)</span> is the <strong>response variable</strong> (e.g.&nbsp;income) for <strong>factor</strong> <span class="math inline">\(i\)</span> (e.g.&nbsp;occupation), <span class="math inline">\(\mu\)</span> is the overall typical value (hereafter referred to as the <strong>common value</strong>) and is usually the mean or median, and <span class="math inline">\(\epsilon_i\)</span> is the <strong>residual</strong>. Next, we will see how the idea of separating the values into components can be expanded to <strong>two-way</strong> (aka <strong>two-factor</strong>) tables.</p>
</section>
<section id="anatomy-of-a-two-way-table" class="level2" data-number="28.2">
<h2 data-number="28.2" class="anchored" data-anchor-id="anatomy-of-a-two-way-table"><span class="header-section-number">28.2</span> Anatomy of a two-way table</h2>
<p>Let’s decompose the following table which represents infant mortality rates (per 1000 live births) by region and by a father’s educational attainment for the years 1964 through 1966 (Hoaglin <em>et al.</em>).</p>
<p><img src="img/twoway_01.png" class="img-fluid"></p>
<p>A two-way table is composed of three variables:</p>
<ul>
<li>a <strong>row factor</strong> which has <strong>four levels</strong> in our working example: Northeast, North Central, South and West,</li>
<li>a <strong>column factor</strong> which has <strong>five levels</strong> in our working example: under 8, 9-11, 12, 13-15 and 16 and greater years of education,</li>
<li><strong>response variables</strong> of which we have 4 (rows) x 5 (columns) = 20 all together.</li>
</ul>
<p>A two-way table is an extension to the one-way table described in the introduction where instead of grouping a continuous variable by a single factor category we explore the variable across <strong>two</strong> factor categories.</p>
<p>We can represent the relationship between the response variable, <span class="math inline">\(y\)</span>, and the <em>two</em> factors as:</p>
<p><span class="math display">\[
y_{ij} = \mu + \alpha_i + \beta_j + \epsilon_{ij}
\]</span></p>
<p>where <span class="math inline">\(y_{ij}\)</span> is the <strong>response variable</strong> for row <span class="math inline">\(i\)</span> and column <span class="math inline">\(j\)</span>, <span class="math inline">\(\mu\)</span> is the overall typical value (hereafter referred to as the <em>common value</em>), <span class="math inline">\(\alpha_i\)</span> is the <strong>row effect</strong>, <span class="math inline">\(\beta_j\)</span> is the <strong>column effect</strong> and <span class="math inline">\(\epsilon_{ij}\)</span> is the <strong>residual</strong> or value left over after <em>all</em> effects are taken into account.</p>
<p>The goal of this analysis is to decompose the response variable into its respective effects–i.e.&nbsp;the two contributing factors: <em>education of father</em> and <em>region</em>–via an iterative process where row medians and column medians are removed from the response variables repeatedly until the row and column medians approach zero.</p>
</section>
<section id="analysis-workflow" class="level2" data-number="28.3">
<h2 data-number="28.3" class="anchored" data-anchor-id="analysis-workflow"><span class="header-section-number">28.3</span> Analysis workflow</h2>
<p>Let’s first create the dataframe.</p>
<div class="cell" data-hash="two_way_cache/html/unnamed-chunk-6_f5a826f622c2f91a29ff02f720232988">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">row.names =</span> <span class="fu">c</span>(<span class="st">"NE"</span>,<span class="st">"NC"</span>,<span class="st">"S"</span>,<span class="st">"W"</span>),</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">ed8       =</span> <span class="fu">c</span>(<span class="fl">25.3</span>,<span class="fl">32.1</span>,<span class="fl">38.8</span>,<span class="fl">25.4</span>), </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">ed9to11   =</span> <span class="fu">c</span>(<span class="fl">25.3</span>,<span class="dv">29</span>,<span class="dv">31</span>,<span class="fl">21.1</span>),</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">ed12      =</span> <span class="fu">c</span>(<span class="fl">18.2</span>,<span class="fl">18.8</span>,<span class="fl">19.3</span>,<span class="fl">20.3</span>),</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">ed13to15  =</span> <span class="fu">c</span>(<span class="fl">18.3</span>,<span class="fl">24.3</span>,<span class="fl">15.7</span>,<span class="dv">24</span>),</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">ed16      =</span> <span class="fu">c</span>(<span class="fl">16.3</span>,<span class="dv">19</span>,<span class="fl">16.8</span>,<span class="fl">17.5</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>                 )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="visualizing-the-data" class="level3" data-number="28.3.1">
<h3 data-number="28.3.1" class="anchored" data-anchor-id="visualizing-the-data"><span class="header-section-number">28.3.1</span> Visualizing the data</h3>
<p>It’s often easier to look at a graphical representation of the data than a tabular one. Even a table as small as this can benefit from a plot.</p>
<p>We will adopt Bill Cleveland’s dotplot for this purpose. R has a built-in dotplot function called <code>dotchart</code>. It requires that the table be stored as a matrix instead of a dataframe; we will therefore convert <code>df</code> to a matrix by wrapping it with the <code>as.matrix()</code> function.</p>
<div class="cell" data-small.mar="true" data-hash="two_way_cache/html/unnamed-chunk-7_14d1690872167f9cd651a876a342ea16">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dotchart</span>( <span class="fu">as.matrix</span>(df), <span class="at">cex=</span><span class="fl">0.7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two_way_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="288"></p>
</div>
</div>
<p>The plot helps visualize any differences in mortality rates across different father educational attainment levels. There seems to be a gradual decrease in child mortality with increasing father educational attainment.</p>
<p>But the plot does not help spot differences across regions (except for the <code>ed12</code> group). We can generate another plot where region becomes the main grouping factor. We do this by wrapping the matrix with the transpose function <code>t()</code>.</p>
<div class="cell" data-small.mar="true" data-hash="two_way_cache/html/unnamed-chunk-8_5a724aeed8ecace6e93a367317113d23">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dotchart</span>( <span class="fu">t</span>(<span class="fu">as.matrix</span>(df)), <span class="at">cex=</span><span class="fl">0.7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two_way_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="288"></p>
</div>
</div>
<p>At first glance, there seems to be higher death rates for the <code>NC</code> and <code>S</code> regions and relatively lower rates for the <code>W</code> and <code>NE</code> regions. But our eyes may be fooled by outliers in the data.</p>
<p>Next, we’ll generate side-by-side boxplots to compare the effects between both categories. Note that we’ll need to create a <em>long</em> version of the table using the <code>tidyr</code> package.</p>
<div class="cell" data-small.mar="true" data-hash="two_way_cache/html/unnamed-chunk-9_42f9c831a6011131f3d0a7e6519ebf81">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>df.l <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Region =</span> <span class="fu">as.factor</span>(<span class="fu">row.names</span>(.)) )  <span class="sc">%&gt;%</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">names_to =</span> <span class="st">"Edu"</span>, <span class="at">values_to =</span> <span class="st">"Deaths"</span>, <span class="sc">-</span>Region) <span class="sc">%&gt;%</span> </span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Edu =</span> <span class="fu">factor</span>(Edu, <span class="at">levels=</span><span class="fu">names</span>(df)))</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># side-by-side plot</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>OP <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Deaths <span class="sc">~</span> Region <span class="sc">+</span> Edu, df.l)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(OP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two_way_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="576"></p>
</div>
</div>
<p>So at this point the plots suggest that there may be a father’s educational attainment effect as well as a regional effect on infant mortality with the former effect being possibly more important.</p>
<p>Next we will attempt to quantify these effects using Tukey’s <strong>median polish</strong>.</p>
</section>
<section id="median-polish" class="level3" data-number="28.3.2">
<h3 data-number="28.3.2" class="anchored" data-anchor-id="median-polish"><span class="header-section-number">28.3.2</span> Median polish</h3>
<p>A median polish is an iterative process whereby we seek to extract the effects from the data into their row and column components. The steps involved in each iteration are described next.</p>
<section id="step-1-compute-overall-median-and-residual-table" class="level4" data-number="28.3.2.1">
<h4 data-number="28.3.2.1" class="anchored" data-anchor-id="step-1-compute-overall-median-and-residual-table"><span class="header-section-number">28.3.2.1</span> Step 1: Compute overall median and residual table</h4>
<p>First, we will compute the median value for <em>all</em> values in the dataset; this will be our first estimate of the <strong>common</strong> value. The resulting median value is placed in the upper left-hand margin of the table. A <strong>residual table</strong> is created by taking the difference between the original value and the overall median.</p>
<p><img src="img/twoway_02.jpg" class="img-fluid"></p>
<p>You’ll also note that the row and column effect values are initially populated with 0 values.</p>
</section>
<section id="step-2-compute-the-row-medians" class="level4" data-number="28.3.2.2">
<h4 data-number="28.3.2.2" class="anchored" data-anchor-id="step-2-compute-the-row-medians"><span class="header-section-number">28.3.2.2</span> Step 2: Compute the row medians</h4>
<p>Next, row medians are computed (shown in red in the following figure) from the residual table.</p>
<p><img src="img/twoway_03.jpg" class="img-fluid"></p>
<p>Note that in addition to computing the row median values for the response variable, we are also computing the median value for the <em>column effects</em> in the upper margin (which happens to be zero since we have no column effect values yet).</p>
</section>
<section id="step-3-create-a-new-residual-table-from-the-row-medians" class="level4" data-number="28.3.2.3">
<h4 data-number="28.3.2.3" class="anchored" data-anchor-id="step-3-create-a-new-residual-table-from-the-row-medians"><span class="header-section-number">28.3.2.3</span> Step 3: Create a new residual table from the row medians</h4>
<p>The row medians are added to the left hand margin of the new residual table (shown in green). These values represent the <em>row effects</em> in this first iteration. A new set of residual values is created from the row medians where each cell takes on the value of the subtraction of the row median from each response variable in that row.</p>
<p><img src="img/twoway_04.jpg" class="img-fluid"></p>
<p>The subtraction is also done for the <em>column effect</em> values (even though all values remain zero) <strong>and</strong> the global median (common effect value).</p>
</section>
<section id="step-4-compute-the-column-medians" class="level4" data-number="28.3.2.4">
<h4 data-number="28.3.2.4" class="anchored" data-anchor-id="step-4-compute-the-column-medians"><span class="header-section-number">28.3.2.4</span> Step 4: Compute the column medians</h4>
<p>Next, column medians are computed (shown in red in the following figure) from the residual table. Note that you are NOT computing the column medians from the original response variables. Note too that we are also computing the median value for the row effect values (left margin).</p>
<p><img src="img/twoway_05.jpg" class="img-fluid"></p>
</section>
<section id="step-5-create-a-new-residual-table-from-the-column-medians" class="level4" data-number="28.3.2.5">
<h4 data-number="28.3.2.5" class="anchored" data-anchor-id="step-5-create-a-new-residual-table-from-the-column-medians"><span class="header-section-number">28.3.2.5</span> Step 5: Create a new residual table from the column medians</h4>
<p>A new residual table is created from the column medians where each new cell takes on the value of the subtraction of the column median from each initial residual value in that column. For example, the first upper-left cell’s residual is <span class="math inline">\(7.0 - 7.4 = -0.4\)</span>.</p>
<p>The column medians are also added to the column effect margin. Note that we are also adding the row effect median value, <code>-0.5</code>, to the <em>common effect</em> cell in the upper left-hand corner.</p>
<p><img src="img/twoway_06.jpg" class="img-fluid"></p>
<p>We have now completed our first row and column smoothing iteration. However, there may be more row and column effects that can be pulled from the residuals. We therefore move on to a second iteration.</p>
</section>
<section id="step-6-second-iteration-row-effects" class="level4" data-number="28.3.2.6">
<h4 data-number="28.3.2.6" class="anchored" data-anchor-id="step-6-second-iteration-row-effects"><span class="header-section-number">28.3.2.6</span> Step 6: Second iteration – row effects</h4>
<p>Next, we compute the row medians from the residuals, then add the <em>column effect</em> median to the top margin (and the common value) and subtract the row medians from the residuals. as in step 3.</p>
<p><img src="img/twoway_06b.jpg" class="img-fluid"></p>
</section>
<section id="step-7-second-iteration-column-effects" class="level4" data-number="28.3.2.7">
<h4 data-number="28.3.2.7" class="anchored" data-anchor-id="step-7-second-iteration-column-effects"><span class="header-section-number">28.3.2.7</span> Step 7: Second iteration – column effects</h4>
<p>To wrap-up the second iteration, we compute the column median values from the residuals then subtract the medians from those residuals. We also add the medians to the row effect values and the common value.</p>
<p><img src="img/twoway_07.jpg" class="img-fluid"></p>
</section>
<section id="when-do-we-stop-iterating" class="level4" data-number="28.3.2.8">
<h4 data-number="28.3.2.8" class="anchored" data-anchor-id="when-do-we-stop-iterating"><span class="header-section-number">28.3.2.8</span> When do we stop iterating?</h4>
<p>The goal is to iterate through the row and column smoothing operations until the row and column effect medians are close to 0. However, Hoaglin <em>et al.</em> (1983) warn against “using unrestrained iteration” and suggest that a few steps should be more than adequate in most instances. In our working example, a third iteration may be warranted. The complete workflow for this third iteration follows.</p>
<p><img src="img/twoway_08.jpg" class="img-fluid"></p>
<p>The final version of the table (along with the column and row values) is shown below:</p>
<p><img src="img/twoway_09.jpg" class="img-fluid"></p>
<p>A progression of each iteration is shown side-by-side in the next figure. The left-most table is the original data showing death rates. The second table shows the outcome of the first round of polishing (including the initial overall median value of 20.2). The third and forth table show the second and third iterations of the smoothing operations. Additional iterations are not deemed necessary given that little more can be extracted from the residuals.</p>
<div class="cell" data-hash="two_way_cache/html/unnamed-chunk-10_90374ca398847c87af3318ada6e07f19">
<div class="cell-output-display">
<p><img src="two_way_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="1056"></p>
</div>
</div>
<p>A few takeway observations from the analysis follow:</p>
<ul>
<li>The <em>common factor</em> ends up contributing the largest effect.</li>
<li>Between <code>Region</code> and <code>Education</code> effects, the latter explains more of the variability in deaths with a range of 7.43 - (-3.7) = 11.13 deaths per 1000 births. The <code>Region</code> effect explains about 2.3 - (-1.46) = 3.76 deaths per 1000 births of the variability in the data.</li>
<li>One abnormally high residual–10.97 deaths above the overall median deaths–is associated with the southern region and an 8<sup>th</sup> grade education.</li>
</ul>
</section>
</section>
<section id="interpreting-the-median-polish" class="level3" data-number="28.3.3">
<h3 data-number="28.3.3" class="anchored" data-anchor-id="interpreting-the-median-polish"><span class="header-section-number">28.3.3</span> Interpreting the median polish</h3>
<p>As noted earlier, a two-way table represents the relationship between the response variable, <span class="math inline">\(y\)</span>, and the two categories as:</p>
<p><span class="math display">\[
y_{ij} = \mu + \alpha_i + \beta_j + \epsilon_{ij}
\]</span></p>
<p>In our working example, <span class="math inline">\(\mu\)</span> = 20.6; <span class="math inline">\(\alpha_i\)</span> = -1.5, 2.6 -0.4, and 0.4 for <span class="math inline">\(i\)</span> = <code>NE</code>, <code>Nc</code>, <code>S</code> and <code>W</code> respectively; <span class="math inline">\(\beta_j\)</span> = 7.6, 6.0, -0.9, 0.2 and -3.5 for <span class="math inline">\(j\)</span> = <code>ed8</code>, <code>ed9to11</code>, <code>ed12</code>, <code>ed13to15</code> and <code>ed16</code> respectively.</p>
<p>The residuals represent the portion of the mortality rates that can’t be explained by either factors.</p>
<p>So the mortality rate in the upper left-hand cell from the original table can be deconstructed as:</p>
<p><img src="img/twoway_10.jpg" class="img-fluid"></p>
<p>The examination of the table suggests that the infant mortality rate is greatest for fathers who did not attain more than 8 years of school (i.e.&nbsp;who has not completed high school) as noted by the high column effect value of 7.6. This is the rate of infant mortality <strong>relative to the overall median</strong> (i.e.&nbsp;on average, 20.6 infants per thousand die every year and the rate goes up to 7.6 + 20.6 for infants whose father has not passed the 8<sup>th</sup> grade). Infants whose father has completed more than 16 years of school (i.e.&nbsp;who has completed college) have a lower rate of mortality as indicated by the low effect value of -3.5 (i.e.&nbsp;3.5 fewer depths than average). The effects from regions also show higher infant mortality rates for North Central and Western regions (with effect values of 2.6 and 0.4 respectively) and lower rates for the northeastern and southern regions; however the regional effect does not appear to be as dominant as that of the father’s educational attainment.</p>
<p>It’s also important to look at the distribution of the residual numbers across the two-way table. One should identify unusually high or low residuals in the table. Such residuals may warrant further investigation (e.g.&nbsp;the high southern region residual value of 10.8 may need further exploration).</p>
</section>
<section id="test-for-non-additivity" class="level3" data-number="28.3.4">
<h3 data-number="28.3.4" class="anchored" data-anchor-id="test-for-non-additivity"><span class="header-section-number">28.3.4</span> Test for non-additivity</h3>
<p>Thus far, we have assumed an additive relationship between the effects (factors). But this additive model may not be the best fit for our data. A good way to test this is by generating a <strong>Tukey Additivity Plot</strong> where we plot residuals vs.&nbsp;the <strong>comparison value</strong>, <span class="math inline">\(cv_{ij}\)</span>, defined as <span class="math inline">\(\alpha_i \beta_j / \mu\)</span>. If the plot is devoid of any obvious trend or pattern we can conclude that our dataset is consistent with an additive model. Such seems to be the case with our working example as shown in the following plot.</p>
<div class="cell" data-small.mar="true" data-hash="two_way_cache/html/unnamed-chunk-11_6f79697b4742d5b385ec14dff0682485">
<div class="cell-output-display">
<p><img src="two_way_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="288"></p>
</div>
</div>
<p>If the diagnostic plot revealed a trend, its shape–or more specifically, its slope–could be used in helping define an appropriate transformation for the data. A rule of thumb is to apply a <span class="math inline">\((1 – slope)\)</span> power transformation to the original data. If the resulting power is not appropriate for the dataset then the <span class="math inline">\(cv_{ij}\)</span> can be added to the additive model as follows:</p>
<p><span class="math display">\[
y_{ij} = \mu + \alpha_i + \beta_j + k(\alpha_i \beta_j / \mu)  + \epsilon_{ij}
\]</span> where the constant <span class="math inline">\(k\)</span> is the slope estimated from the <em>Tukey Additivity</em> plot.</p>
</section>
</section>
<section id="implementing-the-median-polish-in-r" class="level2" data-number="28.4">
<h2 data-number="28.4" class="anchored" data-anchor-id="implementing-the-median-polish-in-r"><span class="header-section-number">28.4</span> Implementing the median polish in R</h2>
<section id="using-base-rs-medpolish" class="level3" data-number="28.4.1">
<h3 data-number="28.4.1" class="anchored" data-anchor-id="using-base-rs-medpolish"><span class="header-section-number">28.4.1</span> Using base R’s <code>medpolish</code></h3>
<p>The steps outlined in the previous section can be easily implemented using pen and paper or a spreadsheet environment for larger datasets. R has a built-in function called <code>medpolish()</code> which does this for us. We can define the maximum number of iterations by setting the <code>maxiter=</code> parameter but note that <code>medpolish</code> will, by default, automatically estimate the best number of iterations for us.</p>
<div class="cell" data-hash="two_way_cache/html/unnamed-chunk-12_b33d0905705eb525559f39c2bdc77e3f">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df.med <span class="ot">&lt;-</span> <span class="fu">medpolish</span>( df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1: 47.1
2: 42.9
3: 42.45
Final: 42.25</code></pre>
</div>
</div>
<p>The median polish ran through 4 iterations–one more than was run in our step-by-step example.</p>
<p>The four values printed to the console gives us the sum of absolute residuals at each iteration. The output from the model is stored in the <code>df.med</code> object. To see its contents , simply type it at the command line.</p>
<div class="cell" data-hash="two_way_cache/html/unnamed-chunk-13_32619a5000872bc3f93103779d81e8c4">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df.med</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Median Polish Results (Dataset: "df")

Overall: 20.775

Row Effects:
    NE     NC      S      W 
-1.475  2.375 -0.350  0.350 

Column Effects:
     ed8  ed9to11     ed12 ed13to15     ed16 
  7.4750   5.9250  -1.1125   0.0750  -3.6250 

Residuals:
      ed8 ed9to11    ed12 ed13to15   ed16
NE -1.475   0.075  0.0125   -1.075  0.625
NC  1.475  -0.075 -3.2375    1.075 -0.525
S  10.900   4.650 -0.0125   -4.800  0.000
W  -3.200  -5.950  0.2875    2.800  0.000</code></pre>
</div>
</div>
<p>All three effects are displayed as well as the residuals (note that the precision returned is greater than that used in our earlier analysis).</p>
<p>To generate the Tukey additivity plot, simply wrap the median polish object with the <code>plot</code> command as in:</p>
<div class="cell" data-small.mar="true" data-hash="two_way_cache/html/unnamed-chunk-14_09c5df91ce09cbcd4b168d3429c6f89a">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>( df.med )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two_way_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="288"></p>
</div>
</div>
</section>
<section id="using-eda_pol" class="level3" data-number="28.4.2">
<h3 data-number="28.4.2" class="anchored" data-anchor-id="using-eda_pol"><span class="header-section-number">28.4.2</span> Using <code>eda_pol</code></h3>
<p>The <code>tukeyedar</code> package has a custom function called <code>eda_pol</code> that will output the polished table as a graphic element.</p>
<p>Unlike the base <code>medpolish</code> function, <code>eda_pol</code> requires that the data be in long form. In creating the long form version of the data, we’ll explicitly set the levels for educational attainment and region.</p>
<div class="cell" data-hash="two_way_cache/html/unnamed-chunk-15_d311464cbe1865576659f04c00e2fe0b">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>grd <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"ed8"</span>, <span class="st">"ed9-11"</span>, <span class="st">"ed12"</span>, <span class="st">"ed13-15"</span>, <span class="st">"ed16"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>reg <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"NE"</span>, <span class="st">"NC"</span>, <span class="st">"S"</span>, <span class="st">"W"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>dfl <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Region =</span>  <span class="fu">factor</span>(<span class="fu">rep</span>( <span class="fu">c</span>(<span class="st">"NE"</span>, <span class="st">"NC"</span>, <span class="st">"S"</span>, <span class="st">"W"</span>), <span class="at">each =</span> <span class="dv">5</span>),</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">levels =</span> reg),</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Education =</span> <span class="fu">factor</span>(<span class="fu">rep</span>( grd , <span class="dv">4</span>), <span class="at">levels =</span> grd),</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Deaths =</span> <span class="fu">c</span>(<span class="fl">25.3</span>, <span class="fl">25.3</span>, <span class="fl">18.2</span>, <span class="fl">18.3</span>, <span class="fl">16.3</span>, <span class="fl">32.1</span>, <span class="dv">29</span>, <span class="fl">18.8</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>                          <span class="fl">24.3</span>, <span class="dv">19</span>, <span class="fl">38.8</span>, <span class="dv">31</span>, <span class="fl">19.3</span>, <span class="fl">15.7</span>, <span class="fl">16.8</span>, <span class="fl">25.4</span>, </span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>                          <span class="fl">21.1</span>, <span class="fl">20.3</span>, <span class="dv">24</span>, <span class="fl">17.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>eda_pol</code> requires that you specify which variables will be mapped to the row and column effects.</p>
<div class="cell" data-hash="two_way_cache/html/unnamed-chunk-16_e9e1b42d5c1c6d97e0de8cc86a753169">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r eda code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tukeyedar)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>df.pol <span class="ot">&lt;-</span> <span class="fu">eda_pol</span>(dfl, <span class="at">row =</span> Region, <span class="at">col =</span> Education , <span class="at">val =</span> Deaths )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="two_way_cache/html/unnamed-chunk-17_0485061db5138b5f8809db9973d13722">
<div class="cell-output-display">
<p><img src="two_way_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="412"></p>
</div>
</div>
<p>Here, the <code>eda_pol</code> function required five iterations which explains the slight difference in values from those generated with the <code>medpolish</code> function. You can control the maximum number of iterations in <code>eda_pol</code> with the <code>maxiter</code> argument.</p>
<p>By default, the column and row values are listed in the same order as they are presented in the input data frame (either defined alphabetically or defined by their levels). You can have the function sort the values by their effect size using the <code>sort</code> argument.</p>
<div class="cell" data-hash="two_way_cache/html/unnamed-chunk-18_a75fa6025b012257c3f986da05c23b65">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r eda code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>df.pol <span class="ot">&lt;-</span> <span class="fu">eda_pol</span>(dfl, <span class="at">row =</span> Region, <span class="at">col =</span> Education, <span class="at">val =</span> Deaths, <span class="at">sort =</span> <span class="cn">TRUE</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="two_way_cache/html/unnamed-chunk-19_a4c8ef0614833d803082b2ce2a30b5b3">
<div class="cell-output-display">
<p><img src="two_way_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="412"></p>
</div>
</div>
<p>The <code>df.pol</code> object is a list that stores output values such as the common, row and column effects.</p>
<div class="cell" data-hash="two_way_cache/html/unnamed-chunk-20_c867fa9dd2b6b52aafdcfef896e2312d">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>df.pol<span class="sc">$</span>global</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20.85</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>df.pol<span class="sc">$</span>row</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Region  effect
1     NE -1.4625
2     NC  2.3000
3      S -0.3500
4      W  0.3500</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>df.pol<span class="sc">$</span>col</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Education   effect
1       ed8  7.43125
2    ed9-11  5.88125
3      ed12 -1.19375
4   ed13-15  0.03125
5      ed16 -3.70000</code></pre>
</div>
</div>
<p>The <code>eda_pol</code> will also output a diagnostic plot.</p>
<div class="cell" data-hash="two_way_cache/html/unnamed-chunk-21_da3b4d2d15c439468dd98d9b3e10f4db">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r eda code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df.pol, <span class="at">type =</span> <span class="st">"diagnostic"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$slope
    cv 
1.3688 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="two_way_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="288"></p>
</div>
</div>
<p>In addition to generating the plot, the function will also return the slope of the fitted line in the console.</p>
<p>For a comprehensive review of the median polish and the <code>eda_pol</code> function, see the <code>eda_pol</code> <a href="https://mgimond.github.io/tukeyedar/articles/polish.html">vignette</a>.</p>
</section>
</section>
<section id="what-if-we-use-the-mean-instead-of-the-median" class="level2" data-number="28.5">
<h2 data-number="28.5" class="anchored" data-anchor-id="what-if-we-use-the-mean-instead-of-the-median"><span class="header-section-number">28.5</span> What if we use the mean instead of the median?</h2>
<p>The procedure is similar with some notable differences. First, we compute the global mean instead of the medians (the common effect) then subtract it from all values in the table. Next, we compute the row means (the row effect) then subtract each mean from all values in its associated row. We finally compute the column means (from the residuals) to give us the column effect. That’s it, unlike the median polish, we do not iterate the smoothing sequences. An example of a “mean” polish applied to our data follows:</p>
<p><img src="img/twoway_11.png" class="img-fluid"></p>
<p>The results differ slightly from those produced using the median polish. Recall that the mean is sensitive to outliers and medians are not. If a robust estimate of the effects is sought, stick with the median polish.</p>
<p>So what can we gain from the “mean” polish? Well, as it turns out, it serves as the basis of the <strong>two-way ANOVA</strong>.</p>
<section id="two-way-anova" class="level3" data-number="28.5.1">
<h3 data-number="28.5.1" class="anchored" data-anchor-id="two-way-anova"><span class="header-section-number">28.5.1</span> Two-way ANOVA</h3>
<p>A two-way ANOVA assesses whether the factors (categories) have a significant effect on the outcome. Its implementation can be conceptualized as a regression analysis where each row and column level is treated as a dummy variable. The computed regression coefficients are the same as the levels computed using the “mean” polish outlined in the previous step except for one notable difference: the ANOVA adds one of the column level values and one of the row level values to the grand mean. It then subtracts those values from their respective row/column effects.</p>
<p><img src="img/twoway_12.png" class="img-fluid"></p>
<p>The resulting row/column levels are the regression coefficients:</p>
<div class="cell" data-hash="two_way_cache/html/unnamed-chunk-22_9857b00948e76646f2b42871c3c01715">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">lm</span>(Deaths <span class="sc">~</span> Education <span class="sc">+</span> Region, dfl)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(M)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     (Intercept)  Educationed9-11    Educationed12 Educationed13-15    Educationed16         RegionNC          RegionS 
          28.255           -3.800          -11.250           -9.825          -13.000            3.960            3.640 
         RegionW 
           0.980 </code></pre>
</div>
</div>
<p>The regression formula takes on the form:</p>
<p><span class="math display">\[
\begin{split}
Deaths = 32.21 - 3.8(ed9to11) -11.25(ed12) -9.83(ed13to15) -13(ed16) \\
         -3.96(RegionNE) -0.320(RegionS)  -2.980(RegionW) + \epsilon_{ij}
\end{split}
\]</span></p>
<p>So, for example, to compute the first value in the raw table (death rate = 25.3) from the formula, substitute the variables as follows:</p>
<p><span class="math display">\[
\begin{split}
Deaths &amp;= 32.21 - 3.8(0) -11.25(0) -9.83(0) -13(0)&amp;&amp; \\
         &amp;-3.96(1) -0.320(0)  -2.980(0) - 3.0&amp; \\
       &amp;= 32.21 -3.96 -3.0&amp;&amp; \\
       &amp;= 25.3&amp;&amp;
\end{split}
\]</span></p>
<p>To assess if any of the factors have a significant effect on the <code>Death</code> variables, simply wrap the regression with an <code>anova()</code> function.</p>
<div class="cell" data-hash="two_way_cache/html/unnamed-chunk-23_ce64700903bec89d35ce4c76b73761d0">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(M)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Deaths
          Df Sum Sq Mean Sq F value  Pr(&gt;F)   
Education  4 478.52 119.630  7.7539 0.00251 **
Region     3  57.44  19.146  1.2410 0.33801   
Residuals 12 185.14  15.428                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The results suggest that the father’s educational attainment has a significant effect on infant mortality (p = 0.0025) whereas the region does not (p = 0.338).</p>
</section>
<section id="visualizing-a-two-way-anova-as-a-table" class="level3" data-number="28.5.2">
<h3 data-number="28.5.2" class="anchored" data-anchor-id="visualizing-a-two-way-anova-as-a-table"><span class="header-section-number">28.5.2</span> Visualizing a two-way ANOVA as a table</h3>
<p>You can view the output of a two-way ANOVA as a “mean polish” table using the <code>eda_pol</code> function. Simply set the <code>stat</code> argument to <code>mean</code>.</p>
<div class="cell" data-hash="two_way_cache/html/unnamed-chunk-24_53efb0f64413d89e047d527343fced23">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r eda code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>df.ano <span class="ot">&lt;-</span> <span class="fu">eda_pol</span>(dfl, <span class="at">row =</span> Region, <span class="at">col =</span> Education, <span class="at">val =</span> Deaths, <span class="at">stat =</span> mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="two_way_cache/html/unnamed-chunk-25_b9389ebf43a5cb11a94361e7db6b0a52">
<div class="cell-output-display">
<p><img src="two_way_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="412"></p>
</div>
</div>
</section>
</section>
<section id="references" class="level2" data-number="28.6">
<h2 data-number="28.6" class="anchored" data-anchor-id="references"><span class="header-section-number">28.6</span> References</h2>
<p><em>Understanding Robust and Exploratory Data Analysis</em>, D.C. Hoaglin, F. Mosteller and J.W. Tukey, 1983.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./discontinuity.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Slicing data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./rmarkdown.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">R markdown document</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Manny Gimond, Creative Commons License <a href="https://creativecommons.org/licenses/by-nc/4.0/"><img src="https://i.creativecommons.org/l/by-nc/4.0/80x15.png" class="img-fluid"></a></div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>